name:                stocks
version:             0.1.0.0
github:              "githubuser/stocks"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/stocks#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.12
- blaze-html >= 0.9 && < 0.10
- optparse-applicative >= 0.14 && < 0.17
- time >= 1.8 && < 1.12
- text >= 1.2 && < 1.3
- fmt >= 0.5 && < 0.7
- cassava >= 0.5 && < 0.6
- colonnade >= 1.1 && < 1.3
- blaze-colonnade >= 1.1 && < 1.3
- Chart >= 1.8 && < 1.10
- Chart-diagrams >= 1.8 && < 1.10

library:
  source-dirs: src

executables:
  stocks-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stocks
    when:
    - condition: false
      other-modules: Paths_stocks

tests:
  stocks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stocks

